name: AvicaRDP

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 350

    steps:
      - name: Direct Avica Setup
        shell: pwsh
        run: |
          Write-Host "Starting Avica setup..." -ForegroundColor Green

          # Download files
          Invoke-WebRequest -Uri "https://gitlab.com/userup908/my-rdp/-/raw/main/setup.py" -OutFile "setup.py"
          Invoke-WebRequest -Uri "https://download.avica.com/AvicaLite_v8.0.8.9.exe" -OutFile "Avica_setup.exe"
          Invoke-WebRequest -Uri "https://gitlab.com/userup908/my-rdp/-/raw/main/show.bat" -OutFile "show.bat"
          Invoke-WebRequest -Uri "https://gitlab.com/userup908/my-rdp/-/raw/main/loop.bat" -OutFile "loop.bat"

          # Python deps
          python.exe -m pip install requests pyautogui telegraph --quiet

          # Enable RDP + firewall + NLA
          Set-ItemProperty -Path 'HKLM:SystemCurrentControlSetControlTerminal Server' -Name "fDenyTSConnections" -Value 0
          Set-ItemProperty -Path 'HKLM:SystemCurrentControlSetControlTerminal ServerWinStationsRDP-Tcp' -Name "UserAuthentication" -Value 1
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          # Set runneradmin password
          net user runneradmin TheDisa1a

          # Silent install Avica (best-effort)
          Start-Process -FilePath "$PWDAvica_setup.exe" -ArgumentList "/S" -WindowStyle Hidden

          # Run setup script
          python "$PWDsetup.py"

          Write-Host "Setup completed." -ForegroundColor Green

      - name: Setup System User
        shell: pwsh
        run: |
          net user runneradmin TheDisa1a
          Write-Host "System user configured" -ForegroundColor Green

      - name: Start Avica Service
        shell: cmd
        run: cmd /c show.bat

      - name: Keep Session Active
        shell: cmd
        run: |
          echo Avica is starting... Look for CONNECTION ID below!
          cmd /c loop.bat
